name: reporting
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  usage: 3.4.1
  tool_base:
    git:
      url: https://github.com/ivan-horchakov/tool_base.git
      ref: master
#  tool_base:
#    path: ../tool_base
dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  mockito: ^4.1.0
  tool_base_test:
    git:
      url: git://github.com/ivan-horchakov/tool_base_test.git
      ref: master
#    path: ../tool_base_test
  args: ^1.5.1
  quiver: ^2.0.5
  meta: ^1.1.8